refactor: 优化安装脚本

diff --git a/dataease/dectl b/dataease/dectl
--- a/dataease/dectl
+++ b/dataease/dectl
@@ -75,15 +75,58 @@ function upgrade() {
       echo -e "\e[32m 检测到GitHub上最新版本为\e[1;33m${latest_version}\e[0;32m 即将执行在线升级...\e[0m"
    fi
    sleep 2s
-   wget -nv -T 60 -t 1 --no-check-certificate https://github.com/dataease/dataease/releases/download/${latest_version}/dataease-${latest_version}-online.tar.gz -O /tmp/dataease-${latest_version}-online.tar.gz
+
+   git_urls=('github.com' 'hub.fastgit.org')
+
+   for git_url in ${git_urls[*]}
+   do
+      success="true"
+      for i in {1..3}
+      do
+         echo -ne "检测 ${git_url} ... ${i} "
+          curl -m 5 -kIs https://${git_url} >/dev/null
+         if [ $? != 0 ];then
+            echo "failed"
+            success="false"
+            break
+         else
+            echo "ok"
+         fi
+      done
+      if [ ${success} == "true" ];then
+         server_url=${git_url}
+         break
+      fi
+   done
+
+   if [ 'x${server_url}' == 'x' ];then
+       echo "没有找到稳定的下载服务器，请稍候重试"
+       exit 1
+   fi
+
+   echo "使用下载服务器 ${server_url}"
+   cd /tmp
+   curl -LOk -m 60 -o dataease-${latest_version}-online.tar.gz  https://${server_url}/dataease/dataease/releases/download/${latest_version}/dataease-${latest_version}-online.tar.gz
    if [ $? -ne 0 ]; then
-      echo -e "\e[31m升级失败:连接GitHub超时！\n可手动下载升级包，然后执行\e[1;33m /bin/bash install.sh \e[0;31m离线升级，也可以重新执行一次 dectl upgrade 命令。\e[0m"
+      echo -e "\e[31m升级失败:连接下载服务器超时！\n可手动下载升级包，然后执行\e[1;33m /bin/bash install.sh \e[0;31m离线升级，也可以重新执行一次 dectl upgrade 命令。\e[0m"
       return 2
    fi
-   cd /tmp
+
+   if [ ! -f dataease-${latest_version}-online.tar.gz ];then
+      echo "下载在线安装包失败，请试试重新执行一次安装命令。"
+      exit 1
+   fi
+
    tar zxvf dataease-${latest_version}-online.tar.gz
+   if [ $? != 0 ];then
+      echo "下载在线安装包失败，请试试重新执行一次安装命令。"
+      rm -f dataease-${latest_version}-online.tar.gz
+      exit 1
+   fi
+
    cd dataease-${latest_version}-online
    /bin/bash install.sh
+   cd ..
    rm -rf /tmp/dataease-${latest_version}-online
 }
 
